### ISSUE TITLE
Pick better names for divs

### ISSUE THREAD

**Issue by sangjunp4rk** [dmudy/prj-rev-bwfs-dasmoto#4]
Choose better names than the generic ones you have right now. Right now you named the divs by section followed by the number. This can easily be messed up if you decide to insert a new section above it and you end up having to rename everything. Instead, make the div names be what the section is. If you are planning to preserve the overall outline and just swap out information inside(i.e. Replace text and stuff but keep the design), then it’s fine.

https://github.com/dmudy/prj-rev-bwfs-dasmoto/blob/master/DasmotosArtsAndCrafts/index.html#L12

**Comment by Devin-The-Dev** [comment]
Thanks
