### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by sangjunp4rk** [dmudy/prj-rev-bwfs-dasmoto#5]
Summary Grade: Satisfactory

Good job with your code! I really like the use of indentation and whitespace in your html code! Makes your code very easy to read! Also, good job grouping sections with divs. This makes your code very compartmentalized makes grouping your sections very effective. These organizational skills come in handy as you expand your code. Great start to the Ready program!
 
I included a few notes in both the html and css files for you to think more critically about. First, try to save your images locally instead of adding a link. Saving images adds to the stability of your website because your website is not reliant on the link to be valid all the time. Also, make sure to use the html & sign instead of just &, which is `&amp;.` This is just a convention. Finally, make sure to use css selectors and attributes to modify your css. For example, don't use the generic `a` selector. Instead, pair it with a class or id so that you can reuse the generic `a` selector with another class or id in other places. This will help your code increase in flexibility as your code becomes larger and you have more things to modify and maintain.

**Comment by Devin-The-Dev** [comment]
Thanks for the feedback. This will help better my pursue a career in web development.
